version: "3"
services:
  db:
    image: postgres:15.1
    container_name: sizif-db
    environment:
      POSTGRES_DB: sizifdb
      POSTGRES_USER: sizifUser
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - sizif-db-volume:/var/lib/postgresql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
#    networks:
#      - monitoring
    network_mode: "host"


  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
#    networks:
#      - monitoring
    network_mode: "host"

volumes:
  sizif-db-volume: {}
  prometheus_data: {}
  grafana-data: {}

networks:
  monitoring:
    external: false